### PR TITLE
If custom fonts are included, refresh helper will update every time.

### PR DESCRIPTION
**Pull request by timmywil**
Refresh helper now checks all files except fonts.

### CODE REVIEW

**Comment by trvsdnn** [comment]
What type of font caused this?

I haven't been able to reproduce the behavior yet.

**Comment by timmywil** [comment]
It was a combination somehow.  Having one font file was not enough.  I got my font collection from http://www.font2web.com/

**Comment by trvsdnn** [comment]
It's because the clocks at font2web.com are wrong. It sets the modified date to be one day in the future, so the refresh helper is always thinking it's new. Just run `touch my-silly-font.otf` to stamp it for now and it'll stop refreshin'.

**Comment by timmywil** [comment]
you rock

**Pull request closed without merging**
